name: usermanager
description: Simple User Management Using Flutter and SQLITE

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2 
  sqflite_common_ffi: ^2.3.0 
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  uuid: ^4.4.0
  crypto: ^3.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true 

  # To add assets to your application, add an assets section:
assets:
  - assets/images/

  # Add permissions for image_picker
permissions:
  - android.permission.CAMERA
  - android.permission.READ_EXTERNAL_STORAGE
  - android.permission.WRITE_EXTERNAL_STORAGE